[Feat] 토큰 재발급/비밀번호 재설정 관련 API 구현
EFUB4-Jukebox/songpin-backend pull request #103
Opened 2024-07-25 20:08 UTC by crHwang0822

# 구현 기능
  - 토큰 재발급 API 구현
  - 비밀번호 재설정 메일 전송 API 구현
  - 링크를 통한 비밀번호 변경 API 구현
  - 중복 코드 리팩터링

# 구현 상태 
  - API 명세서 응답 수정 완료
  - 메일 전송 템플릿 이미지
  <img width="676" alt="image" src="https://github.com/user-attachments/assets/f0d193d2-041e-4b44-ba7d-27a0c674c7b6">

# Resolve
  - #101 

# Memo
- **application.yml 에 추가해야하는 내용을 노션-[자료실] 에 올려놓았습니다.** 
- 중간에 커밋 이름이 잘못된 게 있네요 (a4c258f: 이메일 재설정 → 비밀번호 재설정)

2024-07-26 04:02 UTC, seohyun-lee requested changes
확인했습니다! uri 쪽은 필수 수정이 필요해 request changes 보냈습니다

2024-07-26 04:02 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/member/service/AuthService.java
>              throw new CustomException(ErrorCode.EMAIL_ALREADY_EXISTS);
여기서 checkMemberExistsByEmail 한후에 getActiveMemberByEmail() 해주신 이유가 탈퇴한 회원 예외 처리 던지는 것 때문이신 것 같은데
if (memberService.getActiveMemberByEmail(...)) {...} 이렇게 하면 안 되나요?

2024-07-26 04:02 UTC, seohyun-lee commented on src/main/java/sws/songpin/global/config/SecurityConfig.java
> +            "mail/pw",
/가 빠진 것일까요?

2024-07-26 04:02 UTC, seohyun-lee commented on src/main/java/sws/songpin/global/exception/ErrorCode.java
> +    EXPIRED_ACCESS_TOKEN(401,"만료된 어세스 토큰입니다."),
찾아보니 국내 기술 문서에서는 보통 액세스 라고 부르는 것 같습니다!

2024-07-26 08:22 UTC, crHwang0822 commented on src/main/java/sws/songpin/domain/member/service/AuthService.java
>              throw new CustomException(ErrorCode.EMAIL_ALREADY_EXISTS);
탈퇴한 회원 예외 처리 때문에 호출한 것 맞습니다
getActiveMemberByEmail()  리턴 값이 boolean 이 아닌 Member 이고, 리턴 값으로 조건 검사를 하는 게 아니라 해당 메서드 내에서 조건 검사를 통해 예외처리를 하는 로직이라 저렇게 작성한 것이었는데 말씀하신 것처럼 수정할까요?

2024-07-26 08:46 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/member/service/AuthService.java
>              throw new CustomException(ErrorCode.EMAIL_ALREADY_EXISTS);
다시보니 기존코드대로 놔두는 것도 좋을것같아요! memberRepository 로 쿼리를 두번 보내는것은 불필요한 접근인 것 같아서요

2024-07-26 12:47 UTC, crHwang0822 commented on src/main/java/sws/songpin/domain/member/service/AuthService.java
>              throw new CustomException(ErrorCode.EMAIL_ALREADY_EXISTS);
Optional<member> member = ...
위 코드처럼 작성했던 것 말씀하시는 거죠??
그럼 위 로직대로 작성하되 memberService 에 Optional<Member> 를 리턴하는 getMemberOptionalByEmail() 메서드 작성한 후 해당 메서드를 이용하는 방식으로 구현하려고 하는데 괜찮을까요?!
AuthService에서 memberRepository를 의존하지 않도록 하려는 의도입니닷

2024-07-26 13:02 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/member/service/AuthService.java
>              throw new CustomException(ErrorCode.EMAIL_ALREADY_EXISTS);
아아 넵 좋습니다!!

2024-07-26 13:09 UTC, seohyun-lee approved these changes
확인했습니다!

2024-07-27 03:28 UTC, jud1thDev approved these changes
확인했습니다~!

2024-07-27 09:30 UTC, gkdudans approved these changes
확인했습니다!

2024-07-27 12:36 UTC, merged