[Feat] 플레이리스트 생성, 플레이리스트에 핀 추가, 플레이리스트 상세정보, 플레이리스트 편집, 플레이리스트 삭제
EFUB4-Jukebox/songpin-backend pull request #22
Opened 2024-07-07 16:09 UTC by gkdudans

# 구현 기능
  - 플레이리스트 생성, 플레이리스트에 핀 추가, 플레이리스트 상세정보, 플레이리스트 편집, 플레이리스트 삭제 구현
  - 플레이리스트 상세정보 - PlaylistResponse에 pinList, Songinfo를 중첩 Dto로 구현했으나 추후 수정 가능성 있음
  - 플레이리스트 상세정보 - PlaylistResponse에 isMine, BookmarkId 추가 구현 예정 
  - Errorcode에 `*PLAYLIST_PIN_NOT_FOUND*(404, "플레이리스트 핀을 찾을 수 없습니다")` 추가

# Resolve
  - [week1: Playlist 기능 일부](https://github.com/EFUB4-Jukebox/songpin-backend/issues/17#issue-2393478779)

2024-07-07 17:40 UTC, seohyun-lee requested changes

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<?> getPlaylist(@PathVariable("playlistId") Long playlistId){
PathVariable들은 변하면 안 되는 상수이니 final로 해주시면 좋을 것 같아요!

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/controller/PlaylistController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(playlistService.createPlaylist(requestDto));
ResponseEntity.created() 도 돼요!

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/dto/request/PlaylistPinRequestDto.java
> +        Long pinId
@NotNull 설정 해주어야 Controller의 @Valid가 의미가 있을 것 같습니다! (이건 따로 에러코드 메시지 안 던져도 될 것 같아요)

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/dto/response/PlaylistResponseDto.java
> +        String creatorNickname,
creatorNickname으로 하니 더 명확해져서 좋네요, api 명세서 응답도 수정해주시면 좋을 것 같습니다!

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/entity/Playlist.java
> +    public int pinCount = 0;
이건 혹시 새로운 컬럼인가요? playlistPins.size()을 쓰면 없어도 될 것 같은데, 별도로 저장한다면 ERD 수정이 필요할 것 같습니다..! 그리고 플레이리스트 핀 삭제 시에도 업데이트를 진행해주어야 할 것 같습니다

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/controller/PlaylistController.java
> +        playlistService.addPlaylistPin(playlist, pin.orElse(null));
이 세 줄 다 PlaylistService에서 이루어지면 좋을 것 같습니다!  (Controller는 매우 간단하도록요)

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/service/PlaylistService.java
> +        playlist.setPinCount(pinIndex);
pinCount를 쓰더라도 setter는 없애야 할 것 같습니다!

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/service/PlaylistService.java
> +                .limit(4)
imgPath는 최대 3개입니다!

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/service/PlaylistService.java
> +            playlistPinRepository.save(playlistPin);
리스트를 한번에 saveAll로 저장하는 방법이 있습니다! List<PlaylistPin> newPlaylistPins을 밖에 만들고 newPlaylistPins.add(playlistPin)해서 playlistPinRepository.saveAll(newPlaylistPins); 이런식으로 리팩토링 하면 성능이 더 좋을 것 같아요

2024-07-07 17:40 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/dto/response/PlaylistResponseDto.java
> +    public static PlaylistResponseDto fromEntity(Playlist playlist, List<String> imgPathList, List<PlaylistPinListDto> pinList) {
response dto에서 dto 이렇게 만들 때는 fromEntity가 아닌 from으로 이름 컨벤션 맞추겠습니다..!.! (Entity로부터 만들어지지 않는 경우 있어서)

2024-07-07 18:27 UTC, jud1thDev requested changes

2024-07-07 18:27 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/playlist/controller/PlaylistController.java
> +        playlistService.addPlaylistPin(playlist, pin.orElse(null));
서비스계층으로 이동하고, public Genre getGenreByGenreName(GenreName genreName) {
        return genreRepository.findByGenreName(genreName)
                .orElseThrow(() -> new CustomException(ErrorCode.GENRE_NOT_FOUND));
    } 와 유사한 방식으로 커스텀에러를 사용하면 좋을 것 같습니다.

2024-07-07 18:27 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/playlist/controller/PlaylistController.java
> +    public ResponseEntity<?> getPlaylist(@PathVariable("playlistId") Long playlistId){
dto 사용해서 응답 반환하면 좋을 것 같습니다.

2024-07-07 18:27 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/playlist/service/PlaylistService.java
> +    public void addPlaylistPin(Playlist playlist, Pin pin) {
중복 핀 추가 예외코드 던지는 거 추가하면 될 것 같습니닷

2024-07-07 18:27 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/playlist/service/PlaylistService.java
> +        List<String> imgPathList = playlistPinList.stream()
핀리스트 스트림을 두 번 하고 있는데, 합치는 건 어떨까요..?! 꼭 나눈 이유가 있을까요?

2024-07-07 18:27 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/playlist/service/PlaylistService.java
> +    public void updatePlaylist(Long playlistId, PlaylistUpdateRequestDto requestDto) {
흠 이부분 코드를 조금 더 간략하게 정리할 방법이 없을까요? 삭제&순서조정 -> 일괄저장이 가능한데 비해 순회로직이 너무 반복되는것같은 느낌이 들긴 합니다 ..

2024-07-09 08:13 UTC, gkdudans commented on src/main/java/sws/songpin/domain/playlist/service/PlaylistService.java
> +            playlistPinRepository.save(playlistPin);
플레이리스트에 핀을 하나씩 추가하는 것이어도 saveAll하는 것이 더 좋을까요??

2024-07-09 08:42 UTC, gkdudans commented on src/main/java/sws/songpin/domain/playlist/entity/Playlist.java
> +    public int pinCount = 0;
playlistPins.size() 사용하는 것으로 수정했습니다!

2024-07-10 12:23 UTC, seohyun-lee approved these changes
확인 완료했습니다! `@NotBlank만 수정 부탁드려요~

2024-07-10 12:23 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/entity/Playlist.java
>      @NotNull
NotBlank로 해주세요!

2024-07-10 12:23 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/dto/request/PlaylistRequestDto.java
> +        @NotNull
`@NotBlank(message = "플레이리스트 이름을 입력해주세요.")로 해주시면 좋을 것 같아요! (디스코드 참고)

2024-07-10 12:23 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/playlist/dto/request/PlaylistUpdateRequestDto.java
> +        @NotNull
`@NotBlank(message = "플레이리스트 이름을 입력해주세요.")로 해주시면 좋을 것 같아요! (디스코드 참고)

2024-07-10 14:28 UTC, jud1thDev approved these changes

2024-07-10 15:46 UTC, merged