[Feat] 로그인 API 및 JWT 인증 필터 구현
EFUB4-Jukebox/songpin-backend pull request #28
Opened 2024-07-08 06:50 UTC by crHwang0822

# 구현 기능
  - JWT 발급 
  - JWT 검증
  - 로그인 API 

# 구현 상태 
- 유저가 로그인 시 Access Token과 Refresh Token 발급, 이때 Refresh Token은 Redis에 키(email):값(token) 쌍으로 저장
- Access Token 과 Refresh Token 의 서명에 쓰이는 비밀키는 각각 다르게 구현
---
- 로그인 API 응답
1. 로그인하는 이메일이 DB에 존재하지 않을 때
```json
{
  "timestamp": "2024-07-08T15:48:20.479449900",
  "status": 404,
  "errorCode": "MEMBER_NOT_FOUND",
  "message": "사용자를 찾을 수 없습니다.",
  "path": "/login"
}
```
2. 패스워드가 틀렸을 때
```json
{
  "timestamp": "2024-07-08T15:48:44.070610500",
  "status": 401,
  "errorCode": "LOGIN_FAIL",
  "message": "로그인에 실패했습니다.",
  "path": "/login"
}
```
---
- 토큰 검증 실패 시 응답
1. 만료된 토큰일 때
```json
{
  "errorCode": "EXPIRED_TOKEN",
  "message": "만료된 토큰입니다.",
  "timestamp": "2024-07-08T15:49:23.898279700",
  "status": 401
}
```
2. 유효하지 않은 토큰일 때
```json
{
  "errorCode": "INVALID_TOKEN",
  "message": "유효하지 않은 토큰입니다.",
  "timestamp": "2024-07-08T15:49:47.847155600",
  "status": 401
}
```
# Resolve
- #9

2024-07-08 07:17 UTC, seohyun-lee requested changes

2024-07-08 07:17 UTC, seohyun-lee commented on src/main/java/sws/songpin/global/exception/ErrorCode.java
> +    EXPIRED_TOKEN(401,"만료된 토큰입니다."),
여기가 ErrorCode 충돌 있을 것 같은데 머지 시 확인 부탁드립니다!

2024-07-08 07:17 UTC, seohyun-lee commented on src/main/java/sws/songpin/global/config/SecurityConfig.java
> +            "/signup","/login"
추후 지도나 플레이리스트 상세정보랑 장소 상세정보를 로그인하지 않아도 되도록 열어놓게 되면 같은 uri를 사용하는 api들은 그 내부적으로 보안 확인을 해야 하려나요..? 혹은 uri를 다르게 해야 하려나요

2024-07-08 07:17 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/member/service/MemberService.java
>          return memberRepository.findById(memberId).get();
충돌 비교하셔서 getMemberById에 MEMBER_NOT_FOUND 던져주시면 좋을듯합니다!
MemberService 또는 AuthService에 인증정보 열어서 getCurrentMember 가져오는 것은 나중에 추가 예정이신가요? 좋습니닷!

2024-07-08 07:17 UTC, seohyun-lee commented on src/main/java/sws/songpin/global/auth/CustomUserDetails.java
> +    }
보통 UserDetails 구현하면 메소드 엄청 많이 Override 안하면 에러 나지 않나요..?! 메소드가 다 없는 것 같아 궁금합니다

2024-07-08 07:17 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/member/service/AuthService.java
> +@RequiredArgsConstructor
@Transactional 붙으면 좋을 것 같습니닷

2024-07-08 07:17 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/member/dto/response/LoginResponseDto.java
> +        String refreshToekn
오타났습니다!

2024-07-08 07:26 UTC, crHwang0822 commented on src/main/java/sws/songpin/domain/member/dto/response/LoginResponseDto.java
> +        String refreshToekn
헉 수정하겠습니다 발견해주셔서 감사해요

2024-07-08 07:32 UTC, crHwang0822 commented on src/main/java/sws/songpin/global/auth/CustomUserDetails.java
> +    }
나머지 메서드 (isNonLocked(), isEnabled(), ...) 들은 따로 구현하지 않았을 때에는 default 로 true를 반환하도록 되어있다고 하더라고요! 어차피 나머지 메서드를 프로젝트에서 따로 사용할 일은 없을 것 같아 놔뒀는데, 필요하다고 생각되시면 구현하겠습니닷

2024-07-08 07:33 UTC, crHwang0822 commented on src/main/java/sws/songpin/domain/member/service/MemberService.java
>          return memberRepository.findById(memberId).get();
앗 네 그 부분은 나중에 수정할 예정입니다! 그때 예외처리도 말씀하신대로 해두겠습니다

2024-07-08 07:39 UTC, crhwang822 commented on src/main/java/sws/songpin/global/config/SecurityConfig.java
> +            "/signup","/login"
찾아보니
`http.requestMatchers(HttpMethod.GET,"/map").permitAll() `
위와 같은 방식으로 특정 http 메서드를 갖는 uri 에 관해서도 접근 제어가 가능하다고 하네요!

2024-07-08 07:39 UTC, crHwang0822 commented on src/main/java/sws/songpin/domain/member/service/AuthService.java
> +@RequiredArgsConstructor
네 반영하겠습니다!

2024-07-08 07:41 UTC, seohyun-lee commented on src/main/java/sws/songpin/global/config/SecurityConfig.java
> +            "/signup","/login"
오 감사합니다!!

2024-07-08 07:42 UTC, seohyun-lee commented on src/main/java/sws/songpin/global/auth/CustomUserDetails.java
> +    }
앗 그렇군요! 그럼 따로 구현하지 않으셔도 될 것 같아요 감사합니다~!!

2024-07-08 08:11 UTC, seohyun-lee approved these changes

2024-07-09 08:18 UTC, jud1thDev approved these changes

2024-07-09 17:31 UTC, merged