[Feat] Place 장소 검색, 장소 상세보기 기능 개발
EFUB4-Jukebox/songpin-backend pull request #40
Opened 2024-07-13 18:26 UTC by seohyun-lee

# 구현 기능
  - 장소 검색, 장소 상세보기 API를 개발했습니다.
 
 ### 장소 검색
  - RequestParam으로 sortBy 전달시 검색기준이 소문자여도 대응되도록 하기 위해 string으로 받고 service에 넘겨줄 때 SortBy.from(sortBy) 로 넘겨주었습니다.
  - sortBy 파라미터를 적지 않으면 디폴트는 ACCURACY입니다. offset도 적지 않으면 디폴트는 0입니다.
  - DB 접근해서 정렬하는 것은 네이티브 쿼리를 사용해 구현했습니다.
  - ACCURACY: 사전순 (알파벳 순)
  - NEWEST: 최신 핀 등록 순
  - COUNT: 핀 등록 갯수 많은 순

### 장소 상세보기
  - 현재 excample data set엔 장소와 연결된 모든 핀들의 createdTime값이 insert되지 않아 /places/1 조회시 에러가 날 수 있습니다. createTime도 함께 insert하거나, mysql workbench에서 pin의 createdTime을 apply해주면 정상 작동합니다. 

# Resolve
- #30

2024-07-13 20:07 UTC, seohyun-lee commented
Follow 관련 커밋내역은 Follow 브랜치 Merge한후에 Files Changed에 안걸릴 예정입니닷

2024-07-13 21:12 UTC, jud1thDev requested changes

2024-07-13 21:12 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/dto/response/PlaceDetailsResponseDto.java
> +        Long providerAddressId,
placeId가 아니라 providerAddressId가 필요한가요?

2024-07-13 21:12 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/dto/response/PlaceDetailsResponseDto.java
> +        int pinCount,
SongUnitDto등등 특정 노래에 대한 핀을 세는 부분들에 pinCount가 있어서, 특정 장소에 대해 올라온 핀의 개수는 placePinCount로 바꾸는 건 어떨까요?

2024-07-13 21:12 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/dto/response/PlaceDetailsResponseDto.java
> +        int songCount,
![image](https://github.com/user-attachments/assets/86ba8c4b-23fb-424f-9521-e2e5748d88c8) 이건 피그마 상으로 어느 부분에서 필요한 건가요??

2024-07-13 21:12 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/dto/response/PlaceSearchResponseDto.java
> +        return new PlaceSearchResponseDto(placeCount, placeUnitDtos);
placeCount계산은 어디서 되고있나요?  PlaceSearchResponseDto(placeCount, placeUnitDtos)에서 매개변수로 안 받고 placeList.size()로 직접 계산하는건 어떨까요..?

2024-07-13 21:12 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/controller/PlaceController.java
> +        return ResponseEntity.ok().body(placeService.searchPlaces(keyword, SortBy.from(sortBy), offset));
offset값은 프론트측으로부터 값을 받을 때 변경될 수 있어서 final을 떼야할 것 같아요

2024-07-14 12:23 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/place/dto/response/PlaceDetailsResponseDto.java
> +        Long providerAddressId,
넵 /places/placeId로 들어오는 곳이어서 placeId는 필요없고, 지도에서 해당 위치 찾기 편하도록 providerAddressId도 전송합니다

2024-07-14 12:29 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/place/dto/response/PlaceDetailsResponseDto.java
> +        int songCount,
음 프론트에서 곡 갯수를 알아야 할 것 같아 적었었는데 찾아보니 전달된 배열로 쉽게 연산할수 있나보네요 빼겠습니다!

2024-07-14 12:35 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/place/dto/response/PlaceSearchResponseDto.java
> +        return new PlaceSearchResponseDto(placeCount, placeUnitDtos);
페이징 작업하며 placeCount 뺐습니다!

2024-07-14 13:18 UTC, jud1thDev approved these changes

2024-07-14 13:53 UTC, merged