[Feat] 유저별 지도장소 조회 api, 기존 map api에 장소 필터링 추가 및 리팩토링
EFUB4-Jukebox/songpin-backend pull request #66
Opened 2024-07-20 14:02 UTC by seohyun-lee

# 구현 기능
1. 유저별 지도장소 조회 api를 구현했습니다.
2. 기존 map api에 장소 필터링 추가 및 리팩토링을 진행했습니다.
* Dto를 더 간단하게 구성했습니다.
* Home의 지도장소 조회 api들에 genreNameFilters를 추가하고 장르 필터링 로직을 추가했습니다.
* 지도장소 좌표 같은 경우 FE에 전송하는 데이터 순서가 상관없어서 Set 자료구조를 이용했습니다.
* 기존에 native query로 작성했던 부분을 ProjectionDto를 이용하도록 리팩토링해 보았습니다. 이 방식을 처음 알게 되어 한번 사용해 보았습니다.  (Projection은 dto 만들때 class를 써야 하고 order by listenedDate 등 쿼리문에서 꼭 select에 나타나야 하는 컬럼을 필드로 만들어 주어야 한다는 특징이 있어 Response용은 따로 만들어야 했지만요)

# 구현 상태 (선택)

# Resolve
  - #63

2024-07-21 09:51 UTC, jud1thDev requested changes

2024-07-21 09:51 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/dto/request/MapFetchRecentPeriodRequestDto.java
> +        List<String> genreNameFilters,
GenreName이 아니라 String으로 받는 이유는 무엇인가요?

2024-07-21 09:51 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/controller/MapController.java
>      @GetMapping
찾아보니 GET 메서드와 requestBody가 사용되는 경우도 있긴하지만, 제약이 있는 클라이언트도 많고 일반적인 방식은 아닌 것 같은데  POST를 사용하는 건 어떨까요?
https://blog.naver.com/parkjy76/222907612696

2024-07-21 09:55 UTC, jud1thDev commented on src/main/java/sws/songpin/domain/place/controller/MapController.java
>      @GetMapping
https://2carrot84.github.io/development/get-method-body-request/

2024-07-21 13:48 UTC, seohyun-lee commented on src/main/java/sws/songpin/domain/place/dto/request/MapFetchRecentPeriodRequestDto.java
> +        List<String> genreNameFilters,
커밋 당시 @JsonCreator의 적용시점을 잘 이해하지 못하고 있었던 것 같습니다!

2024-07-21 15:12 UTC, gkdudans approved these changes
확인했습니다

2024-07-22 03:19 UTC, jud1thDev approved these changes
확인했습니다

2024-07-22 03:47 UTC, merged